---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluefin-dx-custom
# description will be included in the image's metadata
description: Bluefin-dx with my tweaks. Made with BlueBuild.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  # - type: rpm-ostree
    # repos:
    #   - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    # install:
    #   - micro
    #   - starship
    # remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - ca.desrt.dconf-editor
        - com.github.iwalton3.jellyfin-media-player
        - com.github.wwmm.easyeffects
      remove:
        - org.gnome.Calendar
        - org.gnome.Connections
        - org.gnome.Contacts
        - org.gnome.Maps
        - org.mozilla.firefox
        - org.mozilla.Thunderbird
    # user: {} # Also add Flathub user repo, but no user packages
  
  - type: script
    snippets:
      - "rm -f /usr/share/applications/discourse.desktop"
      - "rm -f /usr/share/applications/documentation.desktop"
  
  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
      google-fonts:
        - Roboto
        - Roboto Mono
        - Roboto Serif
  
  - type: gnome-extensions
    install:
      - Alphabetical App Grid
      - Coverflow Alt-Tab
      - Hot Edge
      - Just Perfection
      - OSD Volume Number
      - Quick Settings Audio Panel
      - Random Wallpaper
      - Weather O'Clock
    uninstall:
      - Caffeine
      - Dash to Dock
      - GSConnect
      - Logo Menu
      - Search Light
  
  - type: initramfs

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
